title: 立体浮世絵でKABUKU！
description:
  msg:
    - '映画などの映像文化が登場する前の、視覚文化の一つとして'
    - '浮世絵の一種で、多色刷りの錦絵のおもちゃ絵から、'
    - '組上げ灯籠を実際に組み立てて紹介'
show_downloads: false
github:
  is_project_page: false
google_analytics:
theme: jekyll-theme-cayman
